var card=[
 {
   title:"桃花岛分景区",ranking:1,range:22.1,price:139,
   pic:require("../../../assets/img/spot/15.jpg"),
   detail:"可订今日",detail2:"海滨风情",score:4.5,
   comment:111,
  },
 {
   title:"普陀山佛顶山索道",ranking:7,range:18,price:79,
   pic:require("../../../assets/img/spot/16.jpg"),
   detail:"可订今日",detail2:"游普陀山",score:4.5,
   comment:57,
  },
 {
   title:"枸杞岛",ranking:5,range:97.4,price:19,
   pic:require("../../../assets/img/spot/63.jpg"),
   detail:"畅游海岛",detail2:"海滨风情",score:4.3,
   comment:471,
  },
 {
   title:"六井潭",ranking:4,range:87.6,price:55,
   pic:require("../../../assets/img/spot/36.jpg"),
   detail:"可订今日",detail2:"海滨风情",score:4.4,
   comment:666,
  },
 {
   title:"珞珈山",ranking:9,range:23.4,price:99,
   pic:require("../../../assets/img/spot/35.jpg"),
   detail:"可订今日",detail2:"游山玩水",score:4.3,
   comment:101,
  },
 {
   title:"千步沙",ranking:10,range:18.1,price:79,
   pic:require("../../../assets/img/spot/15.jpg"),
   detail:"可订今日",detail2:"有普陀山",score:4.3,
   comment:231,
  },
 {
   title:"佛顶山",ranking:3,range:17.8,price:239,
   pic:require("../../../assets/img/spot/15.jpg"),
   detail:"可订今日",detail2:"游山玩水",score:4.6,
   comment:148,
  },
 {
   title:"桃花岛分景区",ranking:1,range:22.1,price:139,
   pic:require("../../../assets/img/spot/15.jpg"),
   detail:"可订今日",detail2:"海滨风情",score:4.5,
   comment:111,
  },
 {
   title:"桃花岛分景区",ranking:1,range:22.1,price:139,
   pic:require("../../../assets/img/spot/15.jpg"),
   detail:"可订今日",detail2:"海滨风情",score:4.5,
   comment:111,
  },
 {
   title:"桃花岛分景区",ranking:1,range:22.1,price:139,
   pic:require("../../../assets/img/spot/15.jpg"),
   detail:"可订今日",detail2:"海滨风情",score:4.5,
   comment:111,
  },
 {
   title:"桃花岛分景区",ranking:1,range:22.1,price:139,
   pic:require("../../../assets/img/spot/15.jpg"),
   detail:"可订今日",detail2:"海滨风情",score:4.5,
   comment:111,
  },
 {
   title:"桃花岛分景区",ranking:1,range:22.1,price:139,
   pic:require("../../../assets/img/spot/15.jpg"),
   detail:"可订今日",detail2:"海滨风情",score:4.5,
   comment:111,
  },
 {
   title:"桃花岛分景区",ranking:1,range:22.1,price:139,
   pic:require("../../../assets/img/spot/15.jpg"),
   detail:"可订今日",detail2:"海滨风情",score:4.5,
   comment:111,
  },
 {
   title:"桃花岛分景区",ranking:1,range:22.1,price:139,
   pic:require("../../../assets/img/spot/15.jpg"),
   detail:"可订今日",detail2:"海滨风情",score:4.5,
   comment:111,
  },
 {
   title:"桃花岛分景区",ranking:1,range:22.1,price:139,
   pic:require("../../../assets/img/spot/15.jpg"),
   detail:"可订今日",detail2:"海滨风情",score:4.5,
   comment:111,
  },
 {
   title:"桃花岛分景区",ranking:1,range:22.1,price:139,
   pic:require("../../../assets/img/spot/15.jpg"),
   detail:"可订今日",detail2:"海滨风情",score:4.5,
   comment:111,
  },
 {
   title:"桃花岛分景区",ranking:1,range:22.1,price:139,
   pic:require("../../../assets/img/spot/15.jpg"),
   detail:"可订今日",detail2:"海滨风情",score:4.5,
   comment:111,
  },
 {
   title:"桃花岛分景区",ranking:1,range:22.1,price:139,
   pic:require("../../../assets/img/spot/15.jpg"),
   detail:"可订今日",detail2:"海滨风情",score:4.5,
   comment:111,
  },
 {
   title:"桃花岛分景区",ranking:1,range:22.1,price:139,
   pic:require("../../../assets/img/spot/15.jpg"),
   detail:"可订今日",detail2:"海滨风情",score:4.5,
   comment:111,
  },
 {
   title:"桃花岛分景区",ranking:1,range:22.1,price:139,
   pic:require("../../../assets/img/spot/15.jpg"),
   detail:"可订今日",detail2:"海滨风情",score:4.5,
   comment:111,
  },
]

export default card;